### ISSUE TITLE
Packwiz not identifying server properly

### ISSUE THREAD

**Issue by JordanPlayz158** [packwiz/packwiz-installer-bootstrap#10]
I am running packwiz-installer-bootstrap via `java -jar packwiz-installer-bootstrap.jar -g https://path/to/pack.toml` and I have client mods `side = "client"` and both sides mods but yet, I see the server is downloading the client side mods as well, is this expected behavior (if so what is the point of settings the side)? And if not, what determines if the machine is a server or a client? If it is unreliable perhaps there should be a flag added to manually identify the machine as a server or a client? I am running packwiz inside a docker container and am running it through pterodactyl panel (Java 8 image `ghcr.io/pterodactyl/yolks:java_8`).

**Comment by comp500** [comment]
`-g` only disables the GUI. You want the `-s server` flag, to tell packwiz-installer that you're using a server (it defaults to client).

**Comment by JordanPlayz158** [comment]
Oh, the `-s` flag was not defined as an option when using `--help` so I didn't know about the flag but I guess it has probably been added in the 3 years since last github release, but also looks like the latest github release doesn't support `-s`
```java
link.infra.packwiz.installer.deps.commons-cli.MissingArgumentException: Missing argument for option: s
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.checkRequiredArgs(SourceFile:231)
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.handleOption(SourceFile:394)
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.handleShortAndLongOption(SourceFile:467)
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.handleToken(SourceFile:542)
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.parse(SourceFile:712)
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.parse(SourceFile:679)
        at link.infra.packwiz.installer.deps.commons-cli.DefaultParser.parse(SourceFile:660)
        at link.infra.packwiz.installer.Main.startup(SourceFile:38)
        at link.infra.packwiz.installer.Main.<init>(SourceFile:154)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
        at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
        at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
```
and it is not mentioned on the wiki but I assume a wiki entry may be made once the latest stable release includes the `-s` flag

**Comment by JordanPlayz158** [comment]
Ah, I didn't see the `-s` setting in the `--help`, will it be added in the future or maybe already has but not made it into a release yet, or perhaps a wiki entry could be made for how to get packwiz working for server and mention the `-s` setting, but although it does work and does recognize a size change, I still see it is downloading the client side mods?

**Comment by comp500** [comment]
The bootstrap isn't what handles installing the pack, it just updates [packwiz-installer](https://github.com/packwiz/packwiz-installer). That error is just telling you it's missing the `server` part - you need both `-s` and `server` after each other (`-s server`). It is in the docs, though there definitely ought to be a reference page for it: https://packwiz.infra.link/tutorials/installing/packwiz-installer/#using-a-modpack-with-a-server.

The `--help` command is broken at the moment, I'm working on fixing it 😅

**Comment by JordanPlayz158** [comment]
> The bootstrap isn't what handles installing the pack, it just updates [packwiz-installer](https://github.com/packwiz/packwiz-installer). That error is just telling you it's missing the `server` part - you need both `-s` and `server` after each other (`-s server`).
Yeah, sorry, noticed my error and deleted the first message

> It is in the docs, though there definitely ought to be a reference page for it: https://packwiz.infra.link/tutorials/installing/packwiz-installer/#using-a-modpack-with-a-server.
I can't believe I missed that, I went through all the pages, guess I skimmed too fast and missed it, sorry about that

> The `--help` command is broken at the moment, I'm working on fixing it sweat_smile
Thank you for your work :)

Also for this
> although it does work and does recognize a size change, I still see it is downloading the client side mods?
As you said
> The bootstrap isn't what handles installing the pack, it just updates [packwiz-installer](https://github.com/packwiz/packwiz-installer).
I should actually be reporting this to the packwiz-installer repo rather than the bootstrap repo?

**Comment by comp500** [comment]
> I should actually be reporting this to the packwiz-installer repo rather than the bootstrap repo?

Yeah, I'll transfer it now.

> although it does work and does recognize a size change, I still see it is downloading the client side mods?

Hmmm, could you send the `.pw.toml` of one of the files that doesn't work? Also try deleting `packwiz.json`.
