### ISSUE TITLE
Illegal character in path cause errors.

### ISSUE THREAD

**Issue by AxoCode** [packwiz/packwiz-installer-bootstrap#2]
```
[FATAL] Failed to process index file: 
com.google.gson.JsonParseException: Failed to parse URI
	at link.infra.packwiz.installer.metadata.SpaceSafeURIParser.deserialize(SpaceSafeURIParser.kt:20)
	at link.infra.packwiz.installer.metadata.SpaceSafeURIParser.deserialize(SpaceSafeURIParser.kt:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at com.moandjiezana.toml.Toml.to(Toml.java:323)
	at link.infra.packwiz.installer.UpdateManager.processIndex(UpdateManager.kt:254)
	at link.infra.packwiz.installer.UpdateManager.start(UpdateManager.kt:199)
	at link.infra.packwiz.installer.UpdateManager.<init>(UpdateManager.kt:43)
	at link.infra.packwiz.installer.Main.startup(Main.kt:81)
	at link.infra.packwiz.installer.Main.<init>(Main.kt:115)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
	at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
	at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
Caused by: java.net.URISyntaxException: Illegal character in path at index 36: .minecraft/mods/InventoryHUD-fabric-[1.18]%20-3.4.2.jar
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227)
	at java.base/java.net.URI$Parser.parse(URI.java:3186)
	at java.base/java.net.URI.<init>(URI.java:623)
	at link.infra.packwiz.installer.metadata.SpaceSafeURI.<init>(SpaceSafeURI.kt:17)
	at link.infra.packwiz.installer.metadata.SpaceSafeURIParser.deserialize(SpaceSafeURIParser.kt:18)
	... 27 more
```

This is the same as #1, but idk why he closes it.

So it basically caused by illegal characters in the path (`Illegal character in path at index 36: .minecraft/mods/InventoryHUD-fabric-[1.18]%20-3.4.2.jar`). The only way to prevent this, is by making the mod as a normal file (w/o using packwiz)

**Comment by comp500** [comment]
See https://github.com/packwiz/packwiz-installer/issues/2#issuecomment-813106598 (packwiz-installer-bootstrap isn't the right repo for this)

**Comment by AxoCode** [comment]
oh ok, thanks.
